version: "3.8"

services:

  configserver:
    image: anthonylavell/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - PrettyTony
   
  eurekaserver:
    image: anthonylavell/bankeurekaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - PrettyTony
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
  accounts:
    image: anthonylavell/bankaccount:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - PrettyTony
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  loans:
    image: anthonylavell/bankloans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - PrettyTony
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  cards:
    image: anthonylavell/bankcards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - PrettyTony
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
networks:
  PrettyTony: